<?php

/**
 * Color Options for Reno Theme
 *
 * @copyright 2016, Adam Spruijt
 *
 * ProcessWire 2.x
 * Copyright (C) 2010 by Ryan Cramer
 * Licensed under GNU/GPL v2, see LICENSE.TXT
 *
 * http://www.processwire.com
 * http://www.ryancramer.com
 *
 */



class ProcessRenoColors extends Textformatter implements Module, ConfigurableModule {

    public static function getModuleInfo() {
        return array(
            'title' => __("Reno Colors", __FILE__),
            'summary' => __("Allows full control of Reno Theme colors right in admin. And a few other tweaks.", __FILE__),
            'author' => 'Adam Spruijt',
            'version' => 1,
            'autoload' => true,
            'singular' => true
        );
    }


    protected $less;
    protected $compiledFolder; 


    public function init() {

        $this->compiledFolder = "{$this->config->paths->ProcessRenoColors}compiled/";

        // check if lessc is already loaded, fixes exception when less is loaded as default from composer / another source
        if (!class_exists("lessc")) {
            require_once 'lessphp/lessc.inc.php';
        }

        $this->less = new lessc;
        $this->less->setFormatter("compressed");
        


        $this->modules->addHookBefore('saveModuleConfigData', function($event){

            $data = $event->arguments(1);

            // collect the array of colors
            $colors = [];
            foreach ($data as $key => $value) {
                if (strpos($key, "_color") !== false) {
                    $colors["$key"] = $value ?: "#333";
                }
            }

            // overwrite compile hash
            $hash = md5(implode("", $colors));
            $themeFile = "{$this->config->paths->ProcessRenoColors}theme.less";
            
            $compiledFile = "{$this->compiledFolder}theme-{$hash}.css";

            // empty compile folder
            foreach(glob("{$this->compiledFolder}*") as $file){ 
                if(is_file($file)) unlink($file); 
            }

            $this->less->setVariables($colors);
            $this->less->compileFile($themeFile, $compiledFile);
        });  
    }

    public function ready() {
        
        // empty compile folder
        foreach(glob("{$this->compiledFolder}*") as $file){ 
            if(file_exists($file)) $filename = basename($file); 
        }

        if($this->page->template == 'admin') 
            $this->config->styles->add("{$this->config->urls->ProcessRenoColors}compiled/{$filename}");
    }


}